### PR TITLE
Prevent logging from exiting on empty lines

### LINKED ISSUE #10: Logging will fail if an empty line occurs.
The following printf statement will cause logging to fail:

```c
printf("\nHello, World\n");
```

This is because `freadline` does not distinguish between EOF and an empty line.

### LINKED ISSUE #12: Empty lines are ignored by dlog, dslog, and drlog
This might be by design but wanted to bring this up. After #10 is fixed, empty lines will still not be logged. This is due to logic in dlog, dslog, and drlog to skip empty lines.

From my perspective, if someone wanted to log an empty line, I'd vote to have that empty line show up in the log but would love your perspective on this.

### PR DESCRIPTION
**Pull request by schultetwin1**
Before this commit, `freadline` did not distinguish between an empty
line and EOF. This would cause a printf such as

```c
printf("\nHello, World\n");
```

to cause dlog, dslog, or drlog to exit. This change attempts to
separate the EOF case and the empty line case to prevent this logic
from occurring.

Fixes #10
Fixes #12

### CODE REVIEW

File: util.h [hunk 1]
```diff
@@ -21,6 +21,8 @@
 
 #define ERRSTR (strerror (errno))
 
+#define DMON_EOF (-2)
```
Comment (aperezdc) [inline util.h:24]: Using this constant looks clunky to me. End-of-file is not technically an error, that's why zero is returned in that case, and the code here is using the POSIX convention of returning a negative number to indicate an error—it could be any negative number. But the function did in fact read one byte (the delimiter) so returning zero (which means “end of file”) is not quite right.

A better approach would be to make `freaduntil()` include the delimiter in the resulting buffer, and if the returned buffer has `dbuf_size(&linebuf) == 1` then that means that only the delimiter has been put in the buffer. As a bonus, including the new line in the buffer means that it does not need to be added later to the output by hand.

**Review by aperezdc — CHANGES_REQUESTED** [review]
@schultetwin1 Good catch, thanks a lot!

Indeed the logging tools should be more robust and handle empty input lines correctly. I think there is a better way of taking them into account. It would be great if you could try the approach that I suggest below.

Thanks in advance! :muscle:

File: util.h (hunk 1 above)
Comment (schultetwin1) [reply util.h]: > A better approach would be to make...

Great suggestion. I like this solution a lot better! I have updated this PR with that changes. This PR will now fix #10 and #11.

**Review by aperezdc — APPROVED** [review]
That was quick, thanks! The changes look good.
